export enum WeatherTypeEnum {
  clearNightt = "clearNightt",
  sunnyDay = "sunnyDay",
  slightlyCloudy = "slightlyCloudy",
  partlyCloudy = "partlyCloudy",
  mist = "mist",
  fog = "fog",
  highClouds = "highClouds",
  cloudy = "cloudy",
  veryCloudy = "veryCloudy",
  overcast = "overcast",
  lightRainShower = "lightRainShower",
  drizzle = "drizzle",
  lightRain = "lightRain",
  heavyRainShower = "heavyRainShower",
  heavyRain = "heavyRain",
  sleetShower = "sleetShower",
  sleet = "sleet",
  hailShower = "hailShower",
  hail = "hail",
  shower = "shower",
  lightSnow = "lightSnow",
  snow = "snow",
  heavySnowShower = "heavySnowShower",
  heavySnow = "heavySnow",
  thunderShower = "thunderShower",
  thunder = "thunder"
}

